-- MySQL Script generated by MySQL Workbench
-- Sex 16 Jun 2017 11:16:26 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `id` INT NOT NULL,
  `status` INT NULL,
  `type` INT NULL,
  `fee_type` INT NULL,
  `has_bonus_withdraw` INT NULL,
  `is_transparent` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`channel` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `account_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_channel_account_idx` (`account_id` ASC),
  CONSTRAINT `fk_channel_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_form` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `maximum_installments` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `enable` INT NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_member_acc`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tax_applied_to_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tax_applied_to_account` (
  `id` INT NOT NULL,
  `account_id` INT NULL,
  `payment_form_id` INT NULL,
  `fixed` FLOAT NULL,
  `percentual` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tax_applied_to_account_acc_idx` (`account_id` ASC),
  INDEX `fk_tax_applied_to_account_pf_idx` (`payment_form_id` ASC),
  CONSTRAINT `fk_tax_applied_to_account_acc`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tax_applied_to_account_pf`
    FOREIGN KEY (`payment_form_id`)
    REFERENCES `mydb`.`payment_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_fixed_table_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_fixed_table_fee` (
  `id` INT NOT NULL,
  `account_id` INT NULL,
  `payment_form_id` INT NULL,
  `parcel_number` INT NULL,
  `fixed_tax_percentual` FLOAT NULL,
  `parcel_tax_percentual` FLOAT NULL,
  `fixed_tax_value` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_fixed_table_fee_acc_idx` (`account_id` ASC),
  INDEX `fk_account_fixed_table_fee_pf_idx` (`payment_form_id` ASC),
  CONSTRAINT `fk_account_fixed_table_fee_acc`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_fixed_table_fee_pf`
    FOREIGN KEY (`payment_form_id`)
    REFERENCES `mydb`.`payment_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_payment_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_payment_fee` (
  `id` INT NOT NULL,
  `account_id` INT NULL,
  `payment_form_id` INT NULL,
  `fixed` FLOAT NULL,
  `antecipation_percentage` FLOAT NULL,
  `one_parcel` FLOAT NULL,
  `between_two_and_six_parcels` FLOAT NULL,
  `more_than_seven_parcels` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_payment_fee_pf_idx` (`payment_form_id` ASC),
  INDEX `fk_account_payment_fee_acc_idx` (`account_id` ASC),
  CONSTRAINT `fk_account_payment_fee_acc`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_payment_fee_pf`
    FOREIGN KEY (`payment_form_id`)
    REFERENCES `mydb`.`payment_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_channels` (
  `channel_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`channel_id`, `account_id`),
  INDEX `fk_account_channels_acc_idx` (`account_id` ASC),
  CONSTRAINT `fk_account_channels_ch`
    FOREIGN KEY (`channel_id`)
    REFERENCES `mydb`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_channels_acc`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`channel_fixed_table_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`channel_fixed_table_fee` (
  `id` INT NOT NULL,
  `channel_id` INT NULL,
  `payment_form_id` INT NULL,
  `parcel_number` INT NULL,
  `fixed_tax_percentual` FLOAT NULL,
  `parcel_tax_percentual` FLOAT NULL,
  `fixed_tax_value` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_channel_fixed_table_fee_ch_idx` (`channel_id` ASC),
  INDEX `fk_channel_fixed_table_fee_pf_idx` (`payment_form_id` ASC),
  CONSTRAINT `fk_channel_fixed_table_fee_ch`
    FOREIGN KEY (`channel_id`)
    REFERENCES `mydb`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_channel_fixed_table_fee_pf`
    FOREIGN KEY (`payment_form_id`)
    REFERENCES `mydb`.`payment_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fixed_table_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fixed_table_fee` (
  `id` INT NOT NULL,
  `payment_form_id` INT NULL,
  `parcel_number` INT NULL,
  `fixed_tax_percentual` FLOAT NULL,
  `parcel_tax_percentual` FLOAT NULL,
  `fixed_tax_value` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fixed_table_fee_pf_idx` (`payment_form_id` ASC),
  CONSTRAINT `fk_fixed_table_fee_pf`
    FOREIGN KEY (`payment_form_id`)
    REFERENCES `mydb`.`payment_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_installment_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fee` (
  `id` INT NOT NULL,
  `account_id` INT UNSIGNED NULL,
  `payment_form_id` INT UNSIGNED NULL,
  `installment_number` INT UNSIGNED NULL,
  `minimum_fee_value` FLOAT NULL COMMENT 'Taxa mínima cobrada em todo pagamento',
  `variable_fee_percentage` FLOAT NULL COMMENT 'Taxa variável de acordo com o valor e método do pagamento',
  `antecipation_fee_percentage` FLOAT NULL COMMENT 'Taxa percentual aplicada para cada dia antecipado',
  PRIMARY KEY (`id`),
  INDEX `fk_account_tax_acc_idx` (`account_id` ASC),
  INDEX `fk_account_tax_pf_idx` (`payment_form_id` ASC),
  CONSTRAINT `fk_account_tax_acc`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_tax_pf`
    FOREIGN KEY (`payment_form_id`)
    REFERENCES `mydb`.`payment_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
